// Styles:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Fonts:
import localFont from "next/font/local";
const interRoman = localFont({
  variable: "--interRoman-font",
  src: "../fonts/Inter-roman.var.woff2",
  weight: "200 900",
  display: "swap",
  preload: true,
});

// Metadata:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// App layout:
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-neutral-900 text-white antialiased",
          `${interRoman.variable} font-sans`
        )}
      >
        {children}
      </body>
    </html>
  );
}
