import type { Session } from "next-auth";

// Styles:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Fonts:
import { Inter } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: "variable",
  display: "swap",
  preload: true,
});

// Metadata:
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Providers:
import { AuthProvider, SonnerProvider } from "@/providers";

// App layout:
export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session | null;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          "min-h-screen bg-neutral-900 text-white antialiased",
          `${inter.variable} font-sans`
        )}
      >
        <AuthProvider session={session}>{children}</AuthProvider>
        <SonnerProvider />
      </body>
    </html>
  );
}
